[tools]
bat = "latest"
bottom = "latest"
chezmoi = "latest"
curlie = "latest"
delta = "latest"
doggo = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
graphite = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
"pipx:hatch" = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
yq = "latest"
zellij = "latest"
